# Required
host: 'your_host' # May need to include port
version: 'os' # 'Windows' or 'Linux'

#Requires either username and password or token
username: 'your_username@sample.com'
password: 'your_password'

token: 'somelongbearertokenstring'

# Optional. False by default. Set to true to turn on more detailed debugging
debug: False

# Optional. True by default. Set to false to turn off SSL Certificate Verification
verify: True
